### ISSUE TITLE
vagrant rsync-auto error in windows 10 VirtualBox 5

### ISSUE THREAD

**Issue by michaelkacher** [shorrockin/clikr#1]
I am trying to diagnose an issue when the vagrant rsync-auto is run.  Here is the result from powershell whenever I 'up' or try to reload vagrant:

![image](https://cloud.githubusercontent.com/assets/7746523/10239225/2cc45066-6890-11e5-8538-45bfed041b6e.png)

I am invoking the "vagrant up" from the C:\GoProjects\src\github.com\shorrockin\clikr path.  I have confirmed all the file paths and everything seems to match up.

Any assistance in pointing me in the direction of what I need to research to resolve this is appreciated.

**Comment by shorrockin** [comment]
Hmm - Looks like a core problem with vagrant's rsync command. Not sure what the issue might be as I don't have access to a windows box. I would maybe poke around the internet and see if anyone else has issues with vagrant/rysnc/windows.

**Comment by michaelkacher** [comment]
I appreciate your comment.  Looking into it a little more it does appear to be Cygwin rsync issue on windows.  If anyone else runs into this issue here is the ticket to a hacky work-around: https://github.com/mitchellh/vagrant/issues/4073.
